# Generated by Django 5.2.7 on 2025-10-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamestore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description (defaults to short_description if empty)', max_length=160),
        ),
        migrations.AddField(
            model_name='game',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (defaults to title if empty)', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='positive_reviews',
            field=models.IntegerField(default=0, help_text='Percentage of positive reviews (0-100)'),
        ),
        migrations.AddField(
            model_name='game',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
